"""removed unused tables

Revision ID: 02f4267ff141
Revises: dd8f48beae48
Create Date: 2021-04-27 08:16:41.766159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02f4267ff141'
down_revision = 'dd8f48beae48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_customer_return')
    op.drop_index('ix_return_sale_date', table_name='return_sale')
    op.drop_table('return_sale')
    op.drop_table('client_account')
    op.drop_index('ix_account_year', table_name='account')
    op.drop_table('account')
    op.drop_table('order_supplier_return')
    op.drop_index('ix_return_purchase_date', table_name='return_purchase')
    op.drop_table('return_purchase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_purchase',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('total_price', mysql.FLOAT(), nullable=True),
    sa.Column('supplier_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['client.id'], name='return_purchase_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_return_purchase_date', 'return_purchase', ['date'], unique=False)
    op.create_table('order_supplier_return',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_item', mysql.FLOAT(), nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('return_purchase_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supplier_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='order_supplier_return_ibfk_1'),
    sa.ForeignKeyConstraint(['return_purchase_id'], ['return_purchase.id'], name='order_supplier_return_ibfk_2'),
    sa.ForeignKeyConstraint(['supplier_id'], ['client.id'], name='order_supplier_return_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('account',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_account_year', 'account', ['year'], unique=True)
    op.create_table('client_account',
    sa.Column('balance', mysql.FLOAT(), nullable=True),
    sa.Column('outstanding', mysql.FLOAT(), nullable=True),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='client_account_ibfk_1'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='client_account_ibfk_2'),
    sa.PrimaryKeyConstraint('client_id', 'account_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('return_sale',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('total_price', mysql.FLOAT(), nullable=True),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['client.id'], name='return_sale_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_return_sale_date', 'return_sale', ['date'], unique=False)
    op.create_table('order_customer_return',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_item', mysql.FLOAT(), nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('return_sale_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['client.id'], name='order_customer_return_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='order_customer_return_ibfk_2'),
    sa.ForeignKeyConstraint(['return_sale_id'], ['return_sale.id'], name='order_customer_return_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
