"""replacement self join

Revision ID: 1132c6bb4d19
Revises: a3f284ddd0f9
Create Date: 2021-01-24 10:55:04.154927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1132c6bb4d19'
down_revision = 'a3f284ddd0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('replaced_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'product', ['replaced_by_id'], ['id'])
    op.drop_column('product', 'replacement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('replacement', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'replaced_by_id')
    # ### end Alembic commands ###
