"""client details

Revision ID: 17440fc28ac8
Revises: a0cf1e70ba1f
Create Date: 2021-01-23 19:40:58.732398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17440fc28ac8'
down_revision = 'a0cf1e70ba1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('address', sa.String(length=64), nullable=True))
    op.add_column('client', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('client', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'phone_number')
    op.drop_column('client', 'email')
    op.drop_column('client', 'address')
    # ### end Alembic commands ###
