"""float precision v2

Revision ID: 1b1b5df13a37
Revises: 76cbfa9c3701
Create Date: 2021-03-14 19:17:00.553443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b1b5df13a37'
down_revision = '76cbfa9c3701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_customer', 'price_per_item',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_customer', 'price_per_item',
               existing_type=sa.Float(precision=2),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
