"""switched replaces

Revision ID: 1be00accda30
Revises: 1132c6bb4d19
Create Date: 2021-01-24 11:06:45.808961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1be00accda30'
down_revision = '1132c6bb4d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('replaces_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_ibfk_3', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'product', ['replaces_id'], ['id'])
    op.drop_column('product', 'replaced_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('replaced_by_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_ibfk_3', 'product', 'product', ['replaced_by_id'], ['id'])
    op.drop_column('product', 'replaces_id')
    # ### end Alembic commands ###
