"""blob to string

Revision ID: 41ea4f0eff10
Revises: c00f52652056
Create Date: 2021-02-22 18:12:16.332233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ea4f0eff10'
down_revision = 'c00f52652056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'profile_pic',
               existing_type=sa.BLOB(),
               type_=sa.String(length=350),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'profile_pic',
               existing_type=sa.String(length=350),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
