"""root replacement

Revision ID: 7e8240fa731b
Revises: 1be00accda30
Create Date: 2021-01-24 19:05:58.928278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8240fa731b'
down_revision = '1be00accda30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('root_replacement_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'root_replacement_id')
    # ### end Alembic commands ###
