"""sale model

Revision ID: 8017f36d6a67
Revises: 17440fc28ac8
Create Date: 2021-01-23 21:38:58.440463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8017f36d6a67'
down_revision = '17440fc28ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_purchase_official_id', table_name='purchase')
    op.drop_index('ix_purchase_unofficial_id', table_name='purchase')
    op.drop_column('purchase', 'representative_name')
    op.drop_column('purchase', 'official_id')
    op.drop_column('purchase', 'purchase_type')
    op.drop_column('purchase', 'unofficial_id')
    op.drop_column('purchase', 'representative_number')
    op.add_column('sale', sa.Column('official_id', sa.BigInteger(), nullable=True))
    op.add_column('sale', sa.Column('representative_name', sa.String(length=64), nullable=True))
    op.add_column('sale', sa.Column('representative_number', sa.String(length=13), nullable=True))
    op.add_column('sale', sa.Column('sale_type', sa.Boolean(), nullable=True))
    op.add_column('sale', sa.Column('unofficial_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_sale_official_id'), 'sale', ['official_id'], unique=False)
    op.create_index(op.f('ix_sale_unofficial_id'), 'sale', ['unofficial_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_unofficial_id'), table_name='sale')
    op.drop_index(op.f('ix_sale_official_id'), table_name='sale')
    op.drop_column('sale', 'unofficial_id')
    op.drop_column('sale', 'sale_type')
    op.drop_column('sale', 'representative_number')
    op.drop_column('sale', 'representative_name')
    op.drop_column('sale', 'official_id')
    op.add_column('purchase', sa.Column('representative_number', mysql.VARCHAR(length=13), nullable=True))
    op.add_column('purchase', sa.Column('unofficial_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('purchase', sa.Column('purchase_type', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('purchase', sa.Column('official_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('purchase', sa.Column('representative_name', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_purchase_unofficial_id', 'purchase', ['unofficial_id'], unique=False)
    op.create_index('ix_purchase_official_id', 'purchase', ['official_id'], unique=False)
    # ### end Alembic commands ###
