"""added shorot in price-quotas

Revision ID: 82132555fdd0
Revises: 05446f6a1d8b
Create Date: 2021-05-08 10:56:21.258429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82132555fdd0'
down_revision = '05446f6a1d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_quotas', sa.Column('attachment_period', sa.Unicode(length=64), nullable=True))
    op.add_column('price_quotas', sa.Column('payment', sa.Unicode(length=64), nullable=True))
    op.add_column('price_quotas', sa.Column('supply_period', sa.Unicode(length=64), nullable=True))
    op.add_column('price_quotas', sa.Column('supply_place', sa.Unicode(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_quotas', 'supply_place')
    op.drop_column('price_quotas', 'supply_period')
    op.drop_column('price_quotas', 'payment')
    op.drop_column('price_quotas', 'attachment_period')
    # ### end Alembic commands ###
