"""blob to string

Revision ID: 84c4ba974c28
Revises: a609d9c46ea1
Create Date: 2021-02-22 18:06:58.607330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c4ba974c28'
down_revision = 'a609d9c46ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'profile_pic',
               existing_type=sa.BLOB(),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'profile_pic',
               existing_type=sa.String(length=30),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
