"""float precision v3

Revision ID: 9b511cae1d41
Revises: 1b1b5df13a37
Create Date: 2021-03-14 19:18:48.133708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b511cae1d41'
down_revision = '1b1b5df13a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_supplier', 'price_per_item',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('payment_customer', 'amount',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('payment_supplier', 'amount',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('purchase', 'paid',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('purchase', 'total_price',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('sale', 'paid',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('sale', 'total_price',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'total_price',
               existing_type=sa.String(length=20),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sale', 'paid',
               existing_type=sa.String(length=20),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('purchase', 'total_price',
               existing_type=sa.String(length=20),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('purchase', 'paid',
               existing_type=sa.String(length=20),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('payment_supplier', 'amount',
               existing_type=sa.String(length=20),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('payment_customer', 'amount',
               existing_type=sa.String(length=20),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('order_supplier', 'price_per_item',
               existing_type=sa.String(length=20),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
