"""taxes + reductin fields

Revision ID: a3f284ddd0f9
Revises: 8017f36d6a67
Create Date: 2021-01-24 08:13:01.182811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f284ddd0f9'
down_revision = '8017f36d6a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('taxes_included', sa.Boolean(), nullable=True))
    op.add_column('sale', sa.Column('reduction_add', sa.Boolean(), nullable=True))
    op.add_column('sale', sa.Column('taxes_add', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale', 'taxes_add')
    op.drop_column('sale', 'reduction_add')
    op.drop_column('purchase', 'taxes_included')
    # ### end Alembic commands ###
