"""employee table

Revision ID: a609d9c46ea1
Revises: 32159cdfe2b7
Create Date: 2021-02-22 16:32:19.751882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a609d9c46ea1'
down_revision = '32159cdfe2b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=256), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('insurance_number', sa.String(length=50), nullable=True),
    sa.Column('employment_date', sa.DateTime(), nullable=True),
    sa.Column('fixed_salary', sa.Integer(), nullable=True),
    sa.Column('variable_salary', sa.Integer(), nullable=True),
    sa.Column('is_employee', sa.Boolean(), nullable=True),
    sa.Column('profile_pic', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
