"""size changes

Revision ID: afdcf8d6bd82
Revises: 4364f95aa315
Create Date: 2021-03-13 14:37:29.359533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afdcf8d6bd82'
down_revision = '4364f95aa315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'name',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.Unicode(length=50),
               existing_nullable=True)
    op.drop_column('client', 'amount_to_get_paid')
    op.drop_column('client', 'customer_balance')
    op.drop_column('client', 'amount_to_pay')
    op.drop_column('client', 'supplier_balance')
    op.alter_column('purchase', 'representative_email',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('warehouse', 'address',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Unicode(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouse', 'address',
               existing_type=sa.Unicode(length=64),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('purchase', 'representative_email',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)
    op.add_column('client', sa.Column('supplier_balance', mysql.FLOAT(), nullable=True))
    op.add_column('client', sa.Column('amount_to_pay', mysql.FLOAT(), nullable=True))
    op.add_column('client', sa.Column('customer_balance', mysql.FLOAT(), nullable=True))
    op.add_column('client', sa.Column('amount_to_get_paid', mysql.FLOAT(), nullable=True))
    op.alter_column('client', 'name',
               existing_type=sa.Unicode(length=50),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###
