"""price quotas model

Revision ID: b869ff6056c0
Revises: f7aed78bee24
Create Date: 2021-03-19 17:33:16.311531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b869ff6056c0'
down_revision = 'f7aed78bee24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_price', sa.Float(precision=2), nullable=True),
    sa.Column('representative_name', sa.Unicode(length=64), nullable=True),
    sa.Column('representative_number', sa.String(length=13), nullable=True),
    sa.Column('representative_email', sa.String(length=40), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_price_quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_per_item', sa.Float(precision=2), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price_quota_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['price_quota_id'], ['price_quotas.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_price_quota')
    op.drop_table('price_quotas')
    # ### end Alembic commands ###
