"""description to order

Revision ID: c0fe95f87211
Revises: d62aa21633d2
Create Date: 2021-04-25 20:04:57.699420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fe95f87211'
down_revision = 'd62aa21633d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_customer', sa.Column('description', sa.Unicode(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_customer', 'description')
    # ### end Alembic commands ###
