"""blob size 350

Revision ID: f269718ed50f
Revises: 41ea4f0eff10
Create Date: 2021-02-22 18:12:38.229020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f269718ed50f'
down_revision = '41ea4f0eff10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'profile_pic',
               existing_type=mysql.VARCHAR(length=350),
               type_=sa.LargeBinary(length=350),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'profile_pic',
               existing_type=sa.LargeBinary(length=350),
               type_=mysql.VARCHAR(length=350),
               existing_nullable=True)
    # ### end Alembic commands ###
