"""float precision v4

Revision ID: f7aed78bee24
Revises: 9b511cae1d41
Create Date: 2021-03-14 19:19:33.523963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7aed78bee24'
down_revision = '9b511cae1d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_supplier', 'price_per_item',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('payment_customer', 'amount',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('payment_supplier', 'amount',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('purchase', 'paid',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('purchase', 'total_price',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('sale', 'paid',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('sale', 'total_price',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'total_price',
               existing_type=sa.Float(precision=2),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('sale', 'paid',
               existing_type=sa.Float(precision=2),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('purchase', 'total_price',
               existing_type=sa.Float(precision=2),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('purchase', 'paid',
               existing_type=sa.Float(precision=2),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('payment_supplier', 'amount',
               existing_type=sa.Float(precision=2),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('payment_customer', 'amount',
               existing_type=sa.Float(precision=2),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('order_supplier', 'price_per_item',
               existing_type=sa.Float(precision=2),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
